config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('newsletter_app.urls', namespace='newsletter')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

newsletter_app/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from newsletter_app.apps import NewsletterAppConfig
from newsletter_app.views import ClientListView, ClientCreateView, \
    ClientUpdateView, IndexTemplateView, ClientDetailView, ClientDeleteView, \
    NewsletterCreateView, NewsletterListView, NewsletterDetailView, \
    NewsletterUpdateView, NewsletterDeleteView, MassageCreateView, \
    MassageListView, MassageDetailView, MassageUpdateView, MassageDeleteView, \
    LogsCreateView, LogsListView, LogsDetailView, LogsUpdateView, LogsDeleteView

app_name = NewsletterAppConfig.name

urlpatterns = [
    path('', cache_page(60)(IndexTemplateView.as_view()), name='index'),

    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('detail_client/<int:pk>/', ClientDetailView.as_view(), name='detail_client'),
    path('update_client/<int:pk>/', ClientUpdateView.as_view(), name='update_client'),
    path('delete_client/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),

    path('client_list/', ClientListView.as_view(), name='client_list'),


    path('create_newsletter/', NewsletterCreateView.as_view(), name='create_newsletter'),
    path('detail_newsletter/<int:pk>/', NewsletterDetailView.as_view(), name='detail_newsletter'),
    path('update_newsletter/<int:pk>/', NewsletterUpdateView.as_view(), name='update_newsletter'),
    path('delete_newsletter/<int:pk>/', NewsletterDeleteView.as_view(), name='delete_newsletter'),

    path('newsletter_list/', NewsletterListView.as_view(), name='newsletter_list'),


    path('create_massage/', MassageCreateView.as_view(), name='create_massage'),
    path('detail_massage/<int:pk>/', MassageDetailView.as_view(), name='detail_massage'),
    path('update_massage/<int:pk>/', MassageUpdateView.as_view(), name='update_massage'),
    path('delete_massage/<int:pk>/', MassageDeleteView.as_view(), name='delete_massage'),

    path('massage_list/', MassageListView.as_view(), name='massage_list'),


    path('create_logs/', LogsCreateView.as_view(), name='create_logs'),
    path('detail_logs/<int:pk>/', LogsDetailView.as_view(), name='detail_logs'),
    path('update_logs/<int:pk>/', LogsUpdateView.as_view(), name='update_logs'),
    path('delete_logs/<int:pk>/', LogsDeleteView.as_view(), name='delete_logs'),

    path('logs_list/', LogsListView.as_view(), name='logs_list'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (RegisterView, UserUpdateView, generate_new_password,
                         ver_view)


app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password,
         name='generate_new_password'),
    path('verifying/', ver_view),
]

newsletter_app/models.py
from django.conf import settings
from django.db import models


class Client(models.Model):
    fio = models.CharField(max_length=150, verbose_name='ФИО')
    email = models.EmailField(max_length=150, verbose_name='почта')
    comment = models.TextField(verbose_name='комментарий')

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.fio

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Massage(models.Model):
    objects = models.Manager

    title = models.CharField(max_length=40, verbose_name='тема письма')
    content = models.TextField(verbose_name='содержание')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Newsletter(models.Model):
    objects = models.Manager

    PERIODICITY_CHOICES = [
        ('Раз в день', 'Daily'),
        ('Раз в неделю', 'Weekly'),
        ('Раз в меcяц', 'Monthly'),
    ]

    STATUS_CHOICES = [
        ('Завершена', 'Completed'),
        ('Создана', 'Created'),
        ('Запущена', 'Started'),
    ]

    time = models.DateTimeField(verbose_name='время рассылки')
    periodicity = models.CharField(
        max_length=50,
        choices=PERIODICITY_CHOICES,
        verbose_name='периодичность рассылки',
    )

    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        verbose_name='статус рассылки',
    )

    clients = models.ManyToManyField(Client)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    massage = models.ForeignKey(
        Massage,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    def __str__(self):
        return f'{self.time} - {self.status}'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'


class Logs(models.Model):
    objects = models.Manager

    ATTEMPT_CHOICES = [
        ('Успешна', 'Successful'),
        ('Не успешна', 'Not successful'),
    ]

    data_of_attempt = models.DateTimeField(
        auto_now_add=True,
        verbose_name='дата последней попытки',
    )
    status_attempt = models.CharField(
        max_length=50,
        choices=ATTEMPT_CHOICES,
        verbose_name='статус попытки',
    )
    mail_server_response = models.TextField(
        verbose_name='ответ почтового сервера',
        blank=True,
    )
    newsletter = models.ForeignKey(
        Newsletter,
        on_delete=models.CASCADE,
        verbose_name='рассылка',
    )

    def __str__(self):
        return self.status_attempt

    class Meta:
        verbose_name = 'логи'
        verbose_name_plural = 'логи'

    @classmethod
    def log_success(cls, newsletter: Newsletter):
        cls.objects.create(newsletter=newsletter, status_attempt='Успешна')

    @classmethod
    def log_error(cls, newsletter: Newsletter, error_msg: str):
        cls.objects.create(
            newsletter=newsletter,
            status_attempt='Не успешна',
            mail_server_response=error_msg
        )

newsletter_app/forms.py
from django import forms
from newsletter_app.models import Client, Newsletter, Massage, Logs


class ClientForm(forms.ModelForm):

    class Meta:
        model = Client
        fields = '__all__'


class NewsletterForm(forms.ModelForm):

    class Meta:
        model = Newsletter
        fields = '__all__'


class MassageForm(forms.ModelForm):

    class Meta:
        model = Massage
        fields = '__all__'


class LogsForm(forms.ModelForm):

    class Meta:
        model = Logs
        fields = '__all__'


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

newsletter_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (CreateView, UpdateView, ListView,
                                  TemplateView, DetailView, DeleteView)

from newsletter_app.forms import ClientForm, NewsletterForm, MassageForm, \
    LogsForm
from newsletter_app.models import Client, Newsletter, Massage, Logs


class IndexTemplateView(TemplateView):
    template_name = 'newsletter_app/index.html'


"""__________Client Views_____________"""


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('newsletter:client_list')


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client


class ClientUpdateView(LoginRequiredMixin,UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('newsletter:client_list')


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('newsletter:client_list')


class ClientListView(ListView):
    model = Client


"""__________Newsletter Views_____________"""


class NewsletterCreateView(LoginRequiredMixin, CreateView):
    model = Newsletter
    form_class = NewsletterForm
    success_url = reverse_lazy('newsletter:newsletter_list')


class NewsletterDetailView(LoginRequiredMixin, DetailView):
    model = Newsletter


class NewsletterUpdateView(LoginRequiredMixin, UpdateView):
    model = Newsletter
    form_class = NewsletterForm
    success_url = reverse_lazy('newsletter:newsletter_list')


class NewsletterDeleteView(LoginRequiredMixin, DeleteView):
    model = Newsletter
    success_url = reverse_lazy('newsletter:newsletter_list')


class NewsletterListView(ListView):
    model = Newsletter


"""__________Massage Views_____________"""


class MassageCreateView(LoginRequiredMixin, CreateView):
    model = Massage
    form_class = MassageForm
    success_url = reverse_lazy('newsletter:massage_list')


class MassageDetailView(LoginRequiredMixin, DetailView):
    model = Massage


class MassageUpdateView(LoginRequiredMixin, UpdateView):
    model = Massage
    form_class = MassageForm
    success_url = reverse_lazy('newsletter:massage_list')


class MassageDeleteView(LoginRequiredMixin, DeleteView):
    model = Massage
    success_url = reverse_lazy('newsletter:massage_list')


class MassageListView(ListView):
    model = Massage


"""__________Logs Views_____________"""


class LogsCreateView(LoginRequiredMixin, CreateView):
    model = Logs
    form_class = LogsForm
    success_url = reverse_lazy('newsletter:logs_list')


class LogsDetailView(LoginRequiredMixin, DetailView):
    model = Logs


class LogsUpdateView(LoginRequiredMixin, UpdateView):
    model = Logs
    form_class = LogsForm
    success_url = reverse_lazy('newsletter:logs_list')


class LogsDeleteView(LoginRequiredMixin, DeleteView):
    model = Logs
    success_url = reverse_lazy('newsletter:logs_list')


class LogsListView(ListView):
    model = Logs

newsletter_app/templates/newsletter_app/base.html
<!doctype html>
{% load static %}
<html lang="en" data-bs-theme="auto">

<head>
    {% include 'newsletter_app/includes/inc_head.html' %}
</head>

<body>
<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Меню рассылок</h1>
                <p class="lead text-body-secondary">Добавьте адресатов рассылки,
                    и настройки самой рассылки</p>
                <p>
                    <a href="{% url 'newsletter:index' %}"
                       class="btn btn-primary my-2">На главную</a>

                    {% if user.is_authenticated %}

                <form action="{% url 'users:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Выйти</button>
                </form>

                <a class="p-2 btn btn-outline-primary"
                   href="{% url 'users:profile' %}">Профиль</a>

                {% else %}

                <a href="{% url 'users:register' %}"
                   class="btn btn-primary my-2">Регистрация</a>
                <a href="{% url 'users:login' %}"
                   class="btn btn-primary my-2">Войти</a>

                {% endif %}

                </p>
            </div>
        </div>
    </section>

    {% block content %}
    {% endblock content %}

</main>
<footer class="text-body-secondary py-5">
    {% include 'newsletter_app/includes/inc_footer.html' %}
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %} "></script>
</body>
</html>

newsletter_app/templates/newsletter_app/client_confirm_delete.html
{% extends 'newsletter_app/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить клиента "{{ object.fio }} ?</p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'newsletter:client_list' %}"
                           class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

newsletter_app/templates/newsletter_app/client_form.html
{% extends 'newsletter_app/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Добавить адрес для рассылки
                    </div>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if object %}
                        <button type="submit" class="btn btn-primary">Изменить
                        </button>
                        {% else %}
                        <button type="submit" class="btn btn-primary">Создать
                        </button>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

newsletter_app/templates/newsletter_app/index.html
{% extends 'newsletter_app/base.html' %}

{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">Адресаты для рассылок</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'newsletter:create_client' %}"
                                   class="btn btn-sm btn-outline-secondary">
                                    Создать клиента
                                </a>
                                <a href="{% url 'newsletter:client_list' %}"
                                   class="btn btn-sm btn-outline-secondary">
                                    Список всех клиентов
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">Конфигурация рассылки</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'newsletter:create_newsletter' %}"
                                   class="btn btn-sm btn-outline-secondary">
                                    Создать рассылку
                                </a>
                                <a href="{% url 'newsletter:newsletter_list' %}"
                                   class="btn btn-sm btn-outline-secondary">
                                    Список всех рассылок
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">Сообщения для рассылок</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <div class="btn-group">
                                    <a href="{% url 'newsletter:create_massage' %}"
                                       class="btn btn-sm btn-outline-secondary">
                                        Создать сообщение для рассылки
                                    </a>
                                    <a href="{% url 'newsletter:massage_list' %}"
                                       class="btn btn-sm btn-outline-secondary">
                                        Список всех логов
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col mt-2">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">Логи рассылок</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <div class="btn-group">
                                    <a href="{% url 'newsletter:create_logs' %}"
                                       class="btn btn-sm btn-outline-secondary">
                                        Создать логи рассылки
                                    </a>
                                    <a href="{% url 'newsletter:logs_list' %}"
                                       class="btn btn-sm btn-outline-secondary">
                                        Список всех сообщений
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

newsletter_app/templates/newsletter_app/logs_confirm_delete.html
{% extends 'newsletter_app/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить логи "{{ object.title }} ?</p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'newsletter:newsletter_list' %}"
                           class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

newsletter_app/templates/newsletter_app/logs_detail.html
{% extends 'newsletter_app/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Информация о логах
                    </h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Дата последней попытки</td>
                            <td>{{ object.data_of_attempt }}</td>
                        </tr>
                        <tr>
                            <td>Статус</td>
                            <td>{{ object.status_attempt }}</td>
                        </tr>
                        <tr>
                            <td>Ответ почтового сервера</td>
                            <td>{{ object.mail_server_response }}</td>
                        </tr>
                    </table>

                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

newsletter_app/templates/newsletter_app/logs_form.html
{% extends 'newsletter_app/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Добавить логи рассылки
                    </div>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if object %}
                        <button type="submit" class="btn btn-primary">Изменить
                        </button>
                        {% else %}
                        <button type="submit" class="btn btn-primary">Создать
                        </button>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

newsletter_app/templates/newsletter_app/massage_confirm_delete.html
{% extends 'newsletter_app/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить сообщение "{{ object.title }} ?</p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'newsletter:newsletter_list' %}"
                           class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

newsletter_app/templates/newsletter_app/massage_form.html
{% extends 'newsletter_app/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Добавить сообщение для рассылки
                    </div>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if object %}
                        <button type="submit" class="btn btn-primary">Изменить
                        </button>
                        {% else %}
                        <button type="submit" class="btn btn-primary">Создать
                        </button>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

newsletter_app/templates/newsletter_app/massage_list.html
{% extends 'newsletter_app/base.html' %}

{% block content %}

<div class="container">
    <div class="row text-center">
        <div class="col-12 mb-3">
            <a class="btn btn-outline-primary"
               href="{% url 'newsletter:create_massage' %}">
                Добавить сообщение для рассылки </a>
        </div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-2">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">
                            Тема сообщения: {{ object.title }}
                        <p class="card-text">
                            Содержание сообщения: {{ object.content }}
                        <p class="card-text">
                            Сообщение для рассылки: {{ object.newsletter }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'newsletter:detail_massage' object.pk %}">
                                    Посмотреть
                                </a>
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'newsletter:update_massage' object.pk %}">
                                    Изменить
                                </a>
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'newsletter:delete_massage' object.pk %}">
                                    Удалить
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

newsletter_app/templates/newsletter_app/newsletter_confirm_delete.html
{% extends 'newsletter_app/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку "{{ object.time }} ?</p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'newsletter:newsletter_list' %}"
                           class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

newsletter_app/templates/newsletter_app/newsletter_detail.html
{% extends 'newsletter_app/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Информация о рассылке
                    </h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Периодичность</td>
                            <td>{{ object.periodicity }}</td>
                        </tr>
                        <tr>
                            <td>Статус</td>
                            <td>{{ object.status }}</td>
                        </tr>
                        <tr>
                            <td>Время создания</td>
                            <td>{{ object.time }}</td>
                        </tr>
                    </table>

                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

newsletter_app/templates/newsletter_app/newsletter_form.html
{% extends 'newsletter_app/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Добавить рассылку
                    </div>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if object %}
                        <button type="submit" class="btn btn-primary">Изменить
                        </button>
                        {% else %}
                        <button type="submit" class="btn btn-primary">Создать
                        </button>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

newsletter_app/templates/newsletter_app/newsletter_list.html
{% extends 'newsletter_app/base.html' %}

{% block content %}

<div class="container">
    <div class="row text-center">
        <div class="col-12 mb-3">
            <a class="btn btn-outline-primary"
               href="{% url 'newsletter:create_newsletter' %}">
                Добавить рассылку </a>
        </div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-2">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">
                            Время создания: {{ object.time }}
                        <p class="card-text">
                            Периодичность: {{ object.periodicity }}
                        <p class="card-text">
                            Статус: {{ object.status }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'newsletter:detail_newsletter' object.pk %}">
                                    Посмотреть
                                </a>
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'newsletter:update_newsletter' object.pk %}">
                                    Изменить
                                </a>
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'newsletter:delete_newsletter' object.pk %}">
                                    Удалить
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}