config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('newsletter_app.urls', namespace='newsletter')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (RegisterView, UserUpdateView, generate_new_password,
                         ver_view)


app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password,
         name='generate_new_password'),
    path('verifying/', ver_view),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None

    email = models.EmailField(verbose_name='почта', unique=True)
    name = models.CharField(max_length=150, verbose_name='имя',
                            null=True, blank=True)
    avatar = models.ImageField(upload_to='user/', verbose_name='аватар',
                               null=True, blank=True)
    phone = models.CharField(max_length=25, verbose_name='телефон',
                             null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from newsletter_app.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from users.forms import UserRegisterForm, UserForm
from users.models import User
from users.tasks import send_reg_email, new_password, send_new_pass_email


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        form.verified_password = new_password
        new_user = form.save()
        new_user.verified_password = new_password
        send_reg_email(new_user)
        return super().form_valid(form)


def ver_view(request):
    code = int(request.GET.get('code'))
    user = User.objects.get(verified_password=code)
    user.verified = True
    user.save()
    return render(request, 'user/verified.html')


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    success_url = reverse_lazy('users:profile')
    form_class = UserForm

    def get_object(self, queryset=None):
        return self.request.user


def generate_new_password(request):
    send_new_pass_email(request)
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('newsletter:client_list'))

users/templates/users/login.html
{% extends 'newsletter_app/base.html' %}
{% block content %}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Вход
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Войти
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock content %}

users/templates/users/register.html
{% extends 'newsletter_app/base.html' %}
{% block content %}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Регистрация
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Регистрация
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock content %}

users/templates/users/user_form.html
{% extends 'newsletter_app/base.html' %}
{% block content %}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Мой профиль
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Сохранить
                    </button>
                </div>
                <div class="card-footer">
                    <a href="{% url 'users:generate_new_password' %}"
                       class="btn btn-danger">Сгенерировать пароль</a>
                </div>
            </div>
        </div>
    </form>
</div>


{% endblock content %}

users/templates/users/verified.html
{% extends 'newsletter_app/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Спасибо за верификацию!</h1>
</div>

<div class="container-fluid">
    <div class="row text-start">
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Теперь ваша почта
                        подтверждена</h4>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}